kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: appsody-workspace
  namespace: appsody-k8s
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem